### ISSUE TITLE
'namespace' undefined

### ISSUE THREAD

**Issue by supok** [emotionLoop/visualCaptcha-frontend-core#4]
Hi i was trying to implement it in joomla and notice that when i try with out including in joomla framewrok it works very well but when i try to include in joomla it give me an error namespace undefined.

![screen shot 2015-09-26 at 12 43 54 am](https://cloud.githubusercontent.com/assets/878357/10106550/ed4dac04-63e7-11e5-8a7a-d83f8b8fbe68.png)

any suggestion how we can address this issue and what might be the cause of the issue while including in joomla framework.

**Comment by BrunoBernardino** [comment]
It seems the response for the `/start` route is not correct. Can you post the response or check if there are any errors on the server?

Also, are you starting two PHP servers (one for visualCaptcha and another for Joomla), or just one? If just one, you should check the visualCaptcha routes match your server's settings and adjust accordingly.

**Comment by supok** [comment]
i am getting a /start response.
![screen shot 2015-09-26 at 10 30 31 am](https://cloud.githubusercontent.com/assets/878357/10115436/ceee8de4-6439-11e5-89ac-8e08cdbcf3bb.png)

![screen shot 2015-09-26 at 10 29 02 am](https://cloud.githubusercontent.com/assets/878357/10115438/2a4c7d7c-643a-11e5-93c3-e8fbea3a41ed.png)

I am using same php server for both visualCaptcha and Joomla.
Sorry i am not sure how can i check the visualCaptcha routes.

**Comment by BrunoBernardino** [comment]
That looks OK. What is the HTML code you have for the visualCaptcha, what
is the HTML generated (if any, since the error might be happening too
soon), and what is the JS you're using to invoke visualCaptcha?

Also, if you replace the JS file with the unminified version, what line are
you getting an error on?

Thanks.
On Sat, 26 Sep 2015 at 03:34 Supok <notifications@github.com> wrote:

> i am getting a /start response.
> [image: screen shot 2015-09-26 at 10 30 31 am]
> <https://cloud.githubusercontent.com/assets/878357/10115436/ceee8de4-6439-11e5-89ac-8e08cdbcf3bb.png>
>
> [image: screen shot 2015-09-26 at 10 29 02 am]
> <https://cloud.githubusercontent.com/assets/878357/10115438/2a4c7d7c-643a-11e5-93c3-e8fbea3a41ed.png>
>
> I am using same php server for both visualCaptcha and Joomla.
> Sorry i am not sure how can i check the visualCaptcha routes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emotionLoop/visualCaptcha-frontend-core/issues/4#issuecomment-143392384>
> .
>
-- 
http://brunobernardino.com

**Comment by supok** [comment]
Hi a using the following code to invoke visualCaptcha

var captchaEl = $( '#sample-captcha' ).visualCaptcha({
            imgPath: 'visualCaptcha/img',
            captcha: {
                url: 'visualCaptcha/public/',
		numberOfImages: 5,
		//namespace: "signup_form",
                callbacks: {
                    loaded: function( captcha ) {
                        // Avoid adding the hashtag to the URL when clicking/selecting visualCaptcha options
                        $( '#sample-captcha a' ).on( 'click', function( event ) {
                            event.preventDefault();
                        });
                    }
                }
            }
        } );

i am getting an error in visualcaptcha.jquery.src.js file
in line 959.
namespace = captcha.namespace();

**Comment by BrunoBernardino** [comment]
Can you try uncommenting `namespace: "signup_form"` ? Although it should pickup a default.

**Comment by supok** [comment]
sorry no success same error :(

**Comment by BrunoBernardino** [comment]
@supok I'm sorry but I'll need to see more to understand what's wrong. That error you're getting would happen if `$('#sample-captcha')` didn't exist or map to anything.

Can you get me a URL to see this, OR the generated HTML, OR the PHP code/file which generates the page that includes the captcha?
