### ISSUE TITLE
Images not changing on refresh

### ISSUE THREAD

**Issue by meteormanaged** [emotionLoop/visualCaptcha-frontend-core#7]
So I've got visualCaptcha running with an Ember application.

It's the only captcha on the page, all resources seem to load fine, captcha backend is currently the node demo provided.  I've added some middleware to log the request url on that server, which is captured in the below gif, as well as the components being destroyed and rerendered, but still, the same images persist.

Link to actual gif:
http://cl.ly/0d3W3L0R3m1E

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10685349/14859762/a0c4777a-0c73-11e6-81bd-02e9052e7627.png)

**Comment by meteormanaged** [comment]
An interesting note.

As I said, I'm using the demo for the API.  When I go to the demo page, and refresh, it does work correctly.

If I go to my page, refresh, it does not, but if I go to the demo page and have it load a set of images, then return to my page, it will refresh precisely ONCE with new images.

**Comment by meteormanaged** [comment]
Also do note that I'm experiencing this issue with both the vanilla and jQuery packages.

**Comment by BrunoBernardino** [comment]
Thanks for considering visualCaptcha @meteormanaged !

Hmm. This is an interesting issue. It does seem like the session isn't really being recreated, though you _are_ calling the `/start` endpoint.

I don't honestly think this has to do with anything wrong in the ember implementation, as it is making all the requests properly, and in the gif it's visible the DOM is being updated. The data you're receiving is simply the same.

Have you tried spinning up a simple node or php backend locally to try it out with that?

**Comment by meteormanaged** [comment]
Playing around with this a bit more.  It appears that visualCaptcha isn't receiving session information from the Node endpoint because I'm not loading the site itself via the same express setup.  The pictures that were being sent were because there was a session cookie from looking at the demo page, which also explains why the sent images would change after refreshing the demo page, but only once.

I hadn't any plans to use node for the front end application I'm building, since it's built and ember and will be fronted by nginx.  Setting the client-sessions option to httpOnly: false doesn't help with the problem.

Any tips?

**Comment by meteormanaged** [comment]
```
// Throw an error if no session object is passed
    if ( typeof session !== 'object' || ! session ) {
        throw {
            name: 'visualCaptchaException',
            message: 'Cannot initialize visualCaptcha without a valid session object!'
        };
    }
```

So it looks like express isn't passing the session back to the API calls, and then when the next call is sent, session is empty.

The above checks for type, and whether it's true, but doesn't check to see if it's a blank object.

**Comment by meteormanaged** [comment]
Might be prudent to add a check:

`Object.keys(session).length > 0`

**Comment by meteormanaged** [comment]
It appears, looking through the source code, that client-sessions does not actually provide any implementation of httpOnly.  Attempting to use expression-session appears to respect the option, but doesn't appear to work with your library.

**Comment by BrunoBernardino** [comment]
If you're checking https://demo.visualcaptcha.net, it uses the PHP back-end, not the node one.

You can specifically try the node one at http://node.demo.visualcaptcha.net/

Does that make sense?

**Comment by meteormanaged** [comment]
So I worked this out.

Three additions were needed to use your demo node app as an API with the vanilla script.

1 and 2: CORS requires a specific origin to match, as below, as well as Access-Control-Allow-Credentials header, set to true.

```
    app.use( function( req, res, next ) {
        res.header( 'Access-Control-Allow-Origin', 'http://localhost:4200' );
        res.header('Access-Control-Allow-Credentials', 'true');   
    next();
} );`
```
1.  Modification of vanilla.js to set ajaxRequest.withCredentials to true, as below
   
   ```
   define( 'visualcaptcha/xhr-request',[],function() {
   'use strict';
   
   var XMLHttpRequest = window.XMLHttpRequest;
   
   return function( url, callback ) {
       var ajaxRequest = new XMLHttpRequest();
   
       ajaxRequest.open( 'GET', url, true );
       ajaxRequest.withCredentials = true;
       ajaxRequest.onreadystatechange = function() {
           var response;
   
           if ( ajaxRequest.readyState !== 4 || ajaxRequest.status !== 200 ) {
               return;
           }
   
           response = JSON.parse( ajaxRequest.responseText );
           callback( response );
       };
   
       ajaxRequest.send();
   };
   ```
   
   } );

**Comment by BrunoBernardino** [comment]
That's great news @meteormanaged ! That seems specific to your own situation, so I'm closing this.

Let me know if there's anything missing here, and feel free to re-open the issue!

**Comment by vladikoff** [comment]
@meteormanaged thanks for documenting the fix, had the same problem

**Comment by meteormanaged** [comment]
np @vladikoff i'll see if i can't find some time to upload a bit more of a finished demo of my node API solution.
